package xmlite;

import generex.Generex;

public class Main {
	
	private static void writeOnFile(TestSuite list, String outputFileName, String regex){
		
		Writer w = new Writer(list,regex);
		
		if(w.export(outputFileName))
			Grafica.showInfoMessage("Scrittura del file completata.", "Scrittura completata con successo!");
		else
			Grafica.showErrorMessage("Scrittura del file non riuscita!", "Errore scrittura!");
		
	}
		
	private static void newFile(){
		
		String title = Grafica.getFileName("Inserisci l'argomento del file.");
		String regex = Grafica.getRegex("Inserisci la regex");
		TestSuite list = new TestSuite();
		Item newItem;
		int count = 0;
		
		do{
			newItem = Grafica.getItem("Inserisci il nuovo elemento.\n"
									+ "Per terminare l'inserimento, chiudere la finestra. ", 
									"Inserimento nuovo elemento", count);
			if(newItem != null)
				list.add(newItem);
			
			count++;
			
		}while(newItem != null);
		
		writeOnFile(list, title, regex);
	
	}
	
	private static void autogeneratedFile() {
		
		String title = Grafica.getFileName("Inserisci l'argomento del file.");
		String regex = Grafica.getRegex("Inserisci la regex");
		int size = Grafica.getSize("Inserisci il numero di input");
		TestSuite list = new TestSuite();
		
		String input;
		Item newItem;
		
		Generex g = new Generex(regex);
		
		for(int i=0; i<size; i++) {
			
			input = g.random((i+1)*4, (i+1)*4);
			newItem = new Item(input, true);
			list.add(newItem);
		}
		
		writeOnFile(list, title, regex);
		
	}
	
	public static void main(String[] args){
		
		int scelta = Grafica.chooseOperation();
		switch(scelta) {
		
			case 0:
				newFile();
				break;
			case 1:
				autogeneratedFile();
				break;
			default:
				break;
		}
	}

}